### ISSUE TITLE
[Requirements] 4. Get All Detections For An Image Key

### ISSUE THREAD

**Issue by Rubix982** [facebookincubator/mapillary-python-sdk#15]
**Is your feature request related to a problem? Please describe.**
This issue deals with the 4th requirement from the PRD for extracting all the detections within an image using an image key

**Describe the solution you'd like**
The base requirements are,

1. Takes image key as argument
2. Returns JSON with detections (segmentations of the image)

**Describe alternatives you've considered**
NA

**Additional context**
NA

**Comment by Rubix982** [comment]
@cbeddow how to decode the base 64.

**Comment by cbeddow** [comment]
Some context here: https://forum.mapillary.com/t/detection-api-in-v4/4999/

```
import base64

import mapbox_vector_tile

base64_string = "Gjh4AgoGbXB5LW9yKIAgEikIARgDIiMJxCXQFHIMAAocACAHFAkIUQMLGQQvCAkcBQwTDAIGCggADw=="

data = base64.decodebytes(base64_string.encode('utf-8'))

detg = mapbox_vector_tile.decode(data)

print(detg)
```
