### ISSUE TITLE
[Requirements] 9. Get All Images In A Shape

### ISSUE THREAD

**Issue by Rubix982** [facebookincubator/mapillary-python-sdk#20]
**Is your feature request related to a problem? Please describe.**
This issue deals with the 2nd requirement from the PRD extracting all images within a shape

**Describe the solution you'd like**
The base requirements are,

1. Takes a GeoJSON object as argument
2. Same as R07 for other

**Describe alternatives you've considered**
NA

**Additional context**
NA

**Comment by Rubix982** [comment]
Success!

![image](https://user-images.githubusercontent.com/41635766/129143892-47589b36-d75d-40c6-9433-b99ea248b293.png)

![image](https://user-images.githubusercontent.com/41635766/129146392-5cbd63dd-748b-4802-b9db-9d3123762f87.png)

**Comment by cbeddow** [comment]
Great work, looks like it gets all the data very densely. A good way to test as well is to install QGIS from https://qgis.org and you can drop the geojson file in there to view larger amounts of data, like a 10gb file :D
