### ISSUE TITLE
[Utility] Convert coordinates to decimal representation

### ISSUE THREAD

**Issue by OmarMuhammedAli** [facebookincubator/mapillary-python-sdk#91]
**Description**
Required a method to convert from DMS notation to decimal representation for coordinates

**Describe the solution you'd like**
A utility function that takes in `kwargs` of coordinates, converts them, then returns the decimal values.

**Purpose**
To avoid confusion from the users' end about which coordinates format they should input to mapillary driver functions. This way, decimal coordinates are enforced within the business logic.

**Comment by Rubix982** [comment]
Closing. Not needed at the moment. Alternatives in `turfpy` and `mercantile` should be sufficient for now.
